databases:
  - name: cac_app
    plan: free

services:
  - type: web
    plan: free
    name: "cac-tpo-backend"
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn --config src/gconfig.py src.app:app"
    envVars:
      - key: GUNICORN_BIND
        value: "0.0.0.0:8000"
      - key: DATABASE_URL
        fromDatabase:
          name: cac_app
          property: connectionString